### ISSUE TITLE
Digital IPD adjustment

### ISSUE THREAD

**Issue by goldenegg** [CidVonHighwind/VirtualBoyGo#1]
First, let me thank you so much for making this available!

The Virtual Boy had a physical IPD adjustment, to allow custom configuration per user.  The emulator doesn't currently provide a way to control IPD, instead using some default value.  I would like to recommend that this value be configurable, as I find the emulator to cause some eye strain (something I can avoid on a real Virtual Box with the IPD adjustment).  I'm guessing an digital IPD adjustment can help with the strain.

**Comment by DavidJelinek** [comment]
Yes, I have problem in 3D Tetris, I need change IPD here.

**Comment by CidVonHighwind** [comment]
I added IPD adjustment in the new version.

**Comment by DavidJelinek** [comment]
Thx, works perfect.
