### ISSUE TITLE
No longer working on Quest 2 firmware v51+

### ISSUE THREAD

**Issue by FolkSong** [CidVonHighwind/VirtualBoyGo#18]
Quest 2 firmware v51 updated the system to Android 12L which broke compatibility with this app.

If you or anyone is able to get it working again I'm sure it would be appreciated by many, it was such a good fit for the Quest!

Note that Quest 1's final update was v50, so the app should continue to work on that system as-is.

**Comment by ConnieRoseHylia** [comment]
I am also having this issue on the latest firmware. VirtualBoyGo doesn't launch and it has dissapeared from sidequest.

**Comment by uliar** [comment]
@CidVonHighwind :( it's broken for everyone on v51 and up

**Comment by eewokee** [comment]
Please updat to latest SDK. 

This would really be appreciated by many!

**Comment by OzzyHelix** [comment]
I hope this will get fixed if @CidVonHighwind has no interest in fixing it someone might need to fork it

**Comment by NinjaPockets** [comment]
I wish I knew how :( I just got an oculus and got to enjoy having my virtual boy back for one day before it was gone again xD

**Comment by lvonasek** [comment]
https://github.com/lvonasek/VirtualBoyQuest/releases

**Comment by FolkSong** [comment]
Thanks so much Ivonasek, I'll check it out soon!

**Comment by eewokee** [comment]
Wow!! Thanks a lot!!! Very happy with this release!

**Comment by CidVonHighwind** [comment]
https://github.com/CidVonHighwind/VirtualBoyGo/releases/tag/1.5
