### ISSUE TITLE
Please update to latest SDK. My most favorite app is not working anymore....please help.

### ISSUE THREAD

**Issue by eewokee** [CidVonHighwind/VirtualBoyGo#19]
Please update. I really enjoy this app for years.....

Would be much appreciated!!!!!

**Comment by deliyuerek85** [comment]
Yes please!

**Comment by lvonasek** [comment]
https://github.com/lvonasek/VirtualBoyQuest/releases

**Comment by eewokee** [comment]
👏👏👏

**Comment by CidVonHighwind** [comment]
https://github.com/CidVonHighwind/VirtualBoyGo/releases/tag/1.5
