### ISSUE TITLE
Version 1.1. always crashed after selecting any ROM

### ISSUE THREAD

**Issue by DavidJelinek** [CidVonHighwind/VirtualBoyGo#2]
Version 1.1. always crashed after selecting any ROM, version 1.0 is working.

Oculus Go 3.45.70 + gamepad GameSir G3 (https://www.gearbest.com/video-game/pp_257786.html)

**Comment by CidVonHighwind** [comment]
I can't reproduce this issue. Maybe try the new 1.2 version.

**Comment by DavidJelinek** [comment]
Version  1.2 working good for me.
