### ISSUE TITLE
Please fix.

### ISSUE THREAD

**Issue by 900McNuggets** [CidVonHighwind/VirtualBoyGo#20]
the newer quest 2 updates break it due to the update making it android 12 please upgrade to the latest sdk and fix

**Comment by deliyuerek85** [comment]
Yes, please update it. It was a really cool way to experience the VB games in the way thay meant to be experienced.

**Comment by lvonasek** [comment]
https://github.com/lvonasek/VirtualBoyQuest/releases

**Comment by CidVonHighwind** [comment]
https://github.com/CidVonHighwind/VirtualBoyGo/releases/tag/1.5
