### ISSUE TITLE
V1.5 lacks detail of previous releases

### ISSUE THREAD

**Issue by OzzyHelix** [CidVonHighwind/VirtualBoyGo#22]
the image on V1.5 is super dark and lacks the detail of previous releases I am not sure why this is the case
![76b1fd3ab90126179201327bb8a7436e](https://github.com/CidVonHighwind/VirtualBoyGo/assets/29835364/8fb7acbd-c577-4b65-b442-a4442aff19f0)

**Comment by OzzyHelix** [comment]
this is the virtualboyquest fork by comparison 
![b37a5f7925cf0de7ff8b94cf017ac09b](https://github.com/CidVonHighwind/VirtualBoyGo/assets/29835364/5cdefee9-e8ca-4c81-b668-bf3db5725ec5)

**Comment by lvonasek** [comment]
The main difference between my fork and this repo is that I didn't update OVR SDK (=it is probably still compatible with Oculus Go but I don't have the device to confirm). Using the latest SDK versus the old one could theoretically affect the compatibility with Quest Pro and future headsets.

**Comment by OzzyHelix** [comment]
I'm using a Quest 2 I just noticed your fork looked fine but the mainline VirtualBoyGo V1.5 had visual issues with yours having more detail so I'm just confused

**Comment by lvonasek** [comment]
It looks like a wrong colorspace. The details are there, they are just extremely dark.

**Comment by OzzyHelix** [comment]
any way for me to fix that?

**Comment by lvonasek** [comment]
I would try something with this:
https://developer.oculus.com/documentation/native/android/mobile-colorspace/

Or change the framebuffer format.

**Comment by OzzyHelix** [comment]
this might have something to do with the SDK change perhaps colorspace is handled differently in 1.50.0?

**Comment by lvonasek** [comment]
Probably yes, I didn't read the changelogs.

**Comment by CidVonHighwind** [comment]
Should be fixed now. Sorry that it took so long.
