### ISSUE TITLE
can't browse the Quest 2 Directory to locate my Roms folder after update to v1.5.1.

### ISSUE THREAD

**Issue by lordlad** [CidVonHighwind/VirtualBoyGo#23]
can't browse the Quest 2 Directory to locate my Roms folder after update to v1.5.1.

This is despite giving the app file permission when launching it.
Did clear data and reinstall from sidequest still the same.

My roms is already at /Roms/vb.

Is there a file directory change on where the Roms should go?

Screenshots as below.

![Screenshot](https://github.com/CidVonHighwind/VirtualBoyGo/assets/2647193/d40013f7-df28-4ad0-afed-0e7c41724917)
![Sidequest](https://github.com/CidVonHighwind/VirtualBoyGo/assets/2647193/995e5c2e-50a5-4067-8176-78e995d4097f)

**Comment by CidVonHighwind** [comment]
Did you try restarting the App? Looks like there can be a problem with the first launch.
Also can you check if the permissions are enabled like in the image below?
![image](https://github.com/CidVonHighwind/VirtualBoyGo/assets/21128466/7ce158da-528d-4227-bc1a-cdbc2ea3cb1d)

**Comment by deliyuerek85** [comment]
That was a general problem with the previous version and the current quest
version. I was not the only one with this problem. That has already bern
solved with the last VBGo update.

Thanks anyways.

CidVonHighwind ***@***.***> schrieb am So., 19. Nov. 2023,
11:58:

**Comment by lordlad** [comment]
so i did a couple of uninstall and install and finally determined the cause (?).

For whatever reason, if i install the latest v1.5.1 of the app published in SideQuest, it will give me this problem.

If i install the apk downloaded from github, it will be fine.

It's really weird.
