### ISSUE TITLE
Touch controller support for Oculus Quest

### ISSUE THREAD

**Issue by BenMcLean** [CidVonHighwind/VirtualBoyGo#6]
This app works great as-is with a Bluetooth gamepad on Oculus Quest.

The only drawback is that the Touch controllers aren't supported.

It would be really nice to be able to play Virtual Boy games with the Touch controllers.

**Comment by CidVonHighwind** [comment]
I will look into it.

**Comment by BenMcLean** [comment]
Thanks.

I know this is a bit off topic, but another interesting possibility would be a new program for playing Famicom 3D System and SegaScope 3D titles in stereoscopic 3D on the Quest. This can already be done on phone VR via a RetroArch shader which just got written last week by hunterk. (because I nagged him to write it) All it has to do is render one frame for left eye, then the next frame for the right eye, and just keep alternating eyes each frame, and then you can play the 8 or 9 Famicom 3D System games in stereoscopic 3D! SegaScope 3D on the Master System and the lone game Hyper Zone on the SNES do stereoscopic 3D the same way. Should be playable in stereoscopic 3D on VR headsets with relatively little dev work!

I'd be very interested in helping develop this and help with VirtualBoyGo as well if you'd accept my contributions but could use some help getting started since I can't even get VirtualBoyGo to build at this point. I totally understand if you don't have the time or inclination to hand-hold a new developer but if you'd be interested in helping me get started I'd really appreciate it. My email is mclean.ben@gmail.com

**Comment by Gruguir** [comment]
dev great emulator, I hope you'll consider to update it for Quest controllers, the Oculus Touch's design being close to the VB inputs layout.

**Comment by jamescobalt** [comment]
Yup. I assumed it was broken since the touch controllers didn't work. I didn't realize till I checked on Git that it was literally the exact same APK built for Go.

**Comment by BenMcLean** [comment]
I wrote this Powershell script which will pull down all the dependencies to build VirtualBoyGo from source. https://gist.github.com/BenMcLean/f277a12160a5efa3474a4b2a60d0b866

CidVonHighwind updated the source to use the latest Oculus Mobile SDK.

Now all we need is for someone (possibly me) to learn the Oculus Mobile SDK API well enough to actually add the Touch controller support. I've been trying to start learning but it is hard to know where to begin.

**Comment by VRtinker** [comment]
> I wrote this Powershell script which will pull down all the dependencies to build VirtualBoyGo from source. https://gist.github.com/BenMcLean/f277a12160a5efa3474a4b2a60d0b866
> 
> CidVonHighwind updated the source to use the latest Oculus Mobile SDK.
> 
> Now all we need is for someone (possibly me) to learn the Oculus Mobile SDK API well enough to actually add the Touch controller support. I've been trying to start learning but it is hard to know where to begin.

Hi,

I had to add the following on line 95, right above "Invoke-WebRequest -Uri "https://github.com/g-truc/gli/releases/download/0.8.2.0/gli-0.8.2.0.zip" -OutFile "gli-0.8.2.0.zip" to make the script complete without errors:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

I also had to run this first for it to work at all:
Set-ExecutionPolicy Unrestricted
At the time I wasn't using the bat file to run it, so I'm not sure if the "-ExecutionPolicy Bypass" found in the bat would have avoided the need to set to Unrestricted the execution policy.

Regardless, I'm still unable to build this. Using the script, Android Studio keeps complaining about the SDK path, even though it's pointing to the right location in the project AND it's also correctly set in Windows Environment Variables. If I put the pieces together by myself, without using the script, I have no sdk path non-sense issues (the local settings file is not even generated, unlike when using the script) but I get a fatal IDE error instead that I don't know how to address and fix.

I'm very disappointed :-(

EDIT: I managed to successfully compile a working build! Ultimately, it stopped complaining about IDE errors and sdk path missing, but complained about the lack of a keystore file. So I downloaded this file https://raw.githubusercontent.com/facebook/react-native/master/template/android/app/debug.keystore renamed it to "android.debug.keystore" and copied it to the folder \ovr_sdk_mobile_1.23\VrSamples\VirtualBoyGo\Android and everything is well :)

**Comment by BenMcLean** [comment]
> I had to add the following on line 95, right above "Invoke-WebRequest -Uri "https://github.com/g-truc/gli/releases/download/0.8.2.0/gli-0.8.2.0.zip" -OutFile "gli-0.8.2.0.zip" to make the script complete without errors:
> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

I didn't run into that with this script when I ran it but I've needed that on other scripts in the past.

> At the time I wasn't using the bat file to run it, so I'm not sure if the "-ExecutionPolicy Bypass" found in the bat would have avoided the need to set to Unrestricted the execution policy.

Yes, the batch file fixes that. It's a Windows thing for any Powershell.

> Ultimately, it stopped complaining about IDE errors and sdk path missing, but complained about the lack of a keystore file.

I got past that by setting ANDROID_NDK_HOME
